window.TRANSFER_MATH_CONCEPTS = [
  {
    id: "FND-ABS-001",
    subject: "선행 개념",
    unit: "절댓값과 부등식",
    title: "|x-a| < r을 x의 범위로 바꾸기",
    stage: "foundation",
    curriculumOrder: 1,
    prerequisites: [],
    targetSchools: ["공통"],
    source: "편입 수학 앱 학습 소스",
    initialStatus: "unassessed"
  },
  {
    id: "FND-ALG-001",
    subject: "선행 개념",
    unit: "식 변형",
    title: "차의 제곱을 인수분해하기",
    stage: "foundation",
    curriculumOrder: 2,
    prerequisites: [],
    targetSchools: ["공통"],
    source: "편입 수학 앱 학습 소스",
    initialStatus: "understood"
  },
  {
    id: "MATH-DIFF-LIMIT-001",
    subject: "미분학Ⅰ",
    unit: "함수의 극한",
    title: "ε-δ에서 δ가 통제하는 대상",
    stage: "differential-1",
    curriculumOrder: 101,
    prerequisites: ["FND-ABS-001"],
    targetSchools: ["공통"],
    source: "편입 수학 앱 학습 소스",
    initialStatus: "partial"
  },
  {
    id: "MATH-DIFF-LIMIT-002",
    subject: "미분학Ⅰ",
    unit: "함수의 극한",
    title: "극한 목표식을 인수분해하기",
    stage: "differential-1",
    curriculumOrder: 102,
    prerequisites: ["FND-ALG-001"],
    targetSchools: ["공통"],
    source: "편입 수학 앱 학습 소스",
    initialStatus: "understood"
  },
  {
    id: "MATH-DIFF-LIMIT-003",
    subject: "미분학Ⅰ",
    unit: "함수의 극한",
    title: "통제되지 않는 인자 찾기",
    stage: "differential-1",
    curriculumOrder: 103,
    prerequisites: ["MATH-DIFF-LIMIT-002"],
    targetSchools: ["공통"],
    source: "편입 수학 앱 학습 소스",
    initialStatus: "partial"
  },
  {
    id: "MATH-DIFF-LIMIT-004",
    subject: "미분학Ⅰ",
    unit: "함수의 극한",
    title: "x의 근방 제한으로 상한 만들기",
    stage: "differential-1",
    curriculumOrder: 104,
    prerequisites: ["MATH-DIFF-LIMIT-001", "MATH-DIFF-LIMIT-003"],
    targetSchools: ["공통"],
    source: "편입 수학 앱 학습 소스",
    initialStatus: "relearn"
  },
  {
    id: "MATH-DIFF-LIMIT-005",
    subject: "미분학Ⅰ",
    unit: "함수의 극한",
    title: "ε 조건에서 필요한 δ 계산하기",
    stage: "differential-1",
    curriculumOrder: 105,
    prerequisites: ["MATH-DIFF-LIMIT-004"],
    targetSchools: ["공통"],
    source: "편입 수학 앱 학습 소스",
    initialStatus: "unassessed"
  },
  {
    id: "MATH-DIFF-LIMIT-006",
    subject: "미분학Ⅰ",
    unit: "함수의 극한",
    title: "여러 δ 조건을 min으로 결합하기",
    stage: "differential-1",
    curriculumOrder: 106,
    prerequisites: ["MATH-DIFF-LIMIT-005"],
    targetSchools: ["공통"],
    source: "편입 수학 앱 학습 소스",
    initialStatus: "relearn"
  },
  {
    id: "MATH-DIFF-LIMIT-007",
    subject: "미분학Ⅰ",
    unit: "함수의 극한",
    title: "무리함수 극한의 ε-δ 구조",
    stage: "differential-1",
    curriculumOrder: 107,
    prerequisites: ["MATH-DIFF-LIMIT-001"],
    targetSchools: ["공통"],
    source: "2026-08-30 ChatGPT 학습 기록",
    initialStatus: "understood"
  },
  {
    id: "MATH-DIFF-CONT-001",
    subject: "미분학Ⅰ",
    unit: "연속",
    title: "함수의 연속 조건",
    stage: "differential-1",
    curriculumOrder: 120,
    prerequisites: ["MATH-DIFF-LIMIT-006"],
    targetSchools: ["공통"],
    source: "편입수학 커리큘럼",
    initialStatus: "unseen"
  },
  {
    id: "MATH-INT-BASE-001",
    subject: "적분학Ⅰ",
    unit: "적분의 기초",
    title: "부정적분과 원시함수의 관계",
    stage: "integral-1",
    curriculumOrder: 201,
    prerequisites: [],
    targetSchools: ["공통"],
    source: "현재 진도 p.25 이후 진단",
    initialStatus: "unassessed"
  },
  {
    id: "MATH-CALC2-BASE-001",
    subject: "미적분학Ⅱ",
    unit: "진단",
    title: "미적분학Ⅱ 현재 시작점 진단",
    stage: "calculus-2",
    curriculumOrder: 301,
    prerequisites: [],
    targetSchools: ["공통"],
    source: "현재 진도 p.20부터",
    initialStatus: "unassessed"
  },
  {
    id: "MATH-LA-MATRIX-001",
    subject: "선형대수학",
    unit: "행렬",
    title: "행렬의 곱과 연산 순서 진단",
    stage: "linear-algebra",
    curriculumOrder: 401,
    prerequisites: [],
    targetSchools: ["공통"],
    source: "p.53~54 학습 이력 진단",
    initialStatus: "unassessed"
  },
  {
    id: "MATH-LA-VECTOR-001",
    subject: "선형대수학",
    unit: "벡터",
    title: "벡터 기본 개념 진단",
    stage: "linear-algebra",
    curriculumOrder: 430,
    prerequisites: [],
    targetSchools: ["공통"],
    source: "벡터 학습 이력 진단",
    initialStatus: "unassessed"
  },
  {
    id: "MATH-ENG-ODE-001",
    subject: "공업수학",
    unit: "미분방정식",
    title: "미분방정식의 뜻과 해 판별",
    stage: "engineering-math",
    curriculumOrder: 501,
    prerequisites: [],
    targetSchools: ["서강대", "동국대", "서울시립대"],
    source: "학교별 편입 범위 대비",
    initialStatus: "unseen"
  },
  {
    id: "MATH-ENG-LAPLACE-001",
    subject: "공업수학",
    unit: "라플라스 변환",
    title: "라플라스 변환의 역할",
    stage: "engineering-math",
    curriculumOrder: 550,
    prerequisites: ["MATH-ENG-ODE-001"],
    targetSchools: ["서강대"],
    source: "학교별 편입 범위 대비",
    initialStatus: "unseen"
  }
];
