const concept = (id, subject, unit, title, stage, curriculumOrder, prerequisites = [], targetSchools = ["공통"], source = "편입수학 커리큘럼", initialStatus = "unseen") => ({
  id, subject, unit, title, stage, curriculumOrder, prerequisites, targetSchools, source, initialStatus,
});

window.TRANSFER_MATH_CONCEPTS = [
  concept("FND-ABS-001", "선행 개념", "절댓값과 부등식", "|x-a| < r을 x의 범위로 바꾸기", "foundation", 1, [], ["공통"], "편입 수학 앱 학습 소스", "unassessed"),
  concept("FND-ALG-001", "선행 개념", "식 변형", "차의 제곱을 인수분해하기", "foundation", 2, [], ["공통"], "편입 수학 앱 학습 소스", "understood"),
  concept("FND-ALG-002", "선행 개념", "식 변형", "다항식의 기본 인수분해와 약분", "foundation", 3),
  concept("FND-EQ-001", "선행 개념", "방정식", "곱이 0인 방정식과 근 구하기", "foundation", 4, ["FND-ALG-002"]),
  concept("FND-FUNC-001", "선행 개념", "함수", "함수의 합성·역함수와 정의역", "foundation", 5),
  concept("FND-LOG-001", "선행 개념", "지수·로그", "지수법칙과 로그법칙", "foundation", 6),
  concept("FND-TRIG-001", "선행 개념", "삼각함수", "기본 삼각함수 값과 항등식", "foundation", 7),

  concept("MATH-DIFF-LIMIT-001", "미분학Ⅰ", "함수의 극한", "ε-δ에서 δ가 통제하는 대상", "differential-1", 101, ["FND-ABS-001"], ["공통"], "편입 수학 앱 학습 소스", "partial"),
  concept("MATH-DIFF-LIMIT-002", "미분학Ⅰ", "함수의 극한", "극한 목표식을 인수분해하기", "differential-1", 102, ["FND-ALG-001"], ["공통"], "편입 수학 앱 학습 소스", "understood"),
  concept("MATH-DIFF-LIMIT-003", "미분학Ⅰ", "함수의 극한", "통제되지 않는 인자 찾기", "differential-1", 103, ["MATH-DIFF-LIMIT-002"], ["공통"], "편입 수학 앱 학습 소스", "partial"),
  concept("MATH-DIFF-LIMIT-004", "미분학Ⅰ", "함수의 극한", "x의 근방 제한으로 상한 만들기", "differential-1", 104, ["MATH-DIFF-LIMIT-001", "MATH-DIFF-LIMIT-003"], ["공통"], "편입 수학 앱 학습 소스", "relearn"),
  concept("MATH-DIFF-LIMIT-005", "미분학Ⅰ", "함수의 극한", "ε 조건에서 필요한 δ 계산하기", "differential-1", 105, ["MATH-DIFF-LIMIT-004"], ["공통"], "편입 수학 앱 학습 소스", "unassessed"),
  concept("MATH-DIFF-LIMIT-006", "미분학Ⅰ", "함수의 극한", "여러 δ 조건을 min으로 결합하기", "differential-1", 106, ["MATH-DIFF-LIMIT-005"], ["공통"], "편입 수학 앱 학습 소스", "relearn"),
  concept("MATH-DIFF-LIMIT-007", "미분학Ⅰ", "함수의 극한", "무리함수 극한의 ε-δ 구조", "differential-1", 107, ["MATH-DIFF-LIMIT-001"], ["공통"], "2026-08-30 ChatGPT 학습 기록", "understood"),
  concept("MATH-DIFF-LIMIT-008", "미분학Ⅰ", "함수의 극한", "극한의 성질과 직접 대입", "differential-1", 108, ["FND-FUNC-001"]),
  concept("MATH-DIFF-LIMIT-009", "미분학Ⅰ", "함수의 극한", "0/0 꼴에서 인수분해로 극한 구하기", "differential-1", 109, ["FND-ALG-002", "MATH-DIFF-LIMIT-008"]),
  concept("MATH-DIFF-LIMIT-010", "미분학Ⅰ", "함수의 극한", "무리식 극한에서 유리화하기", "differential-1", 110, ["MATH-DIFF-LIMIT-008"]),
  concept("MATH-DIFF-LIMIT-011", "미분학Ⅰ", "함수의 극한", "좌극한·우극한과 극한 존재", "differential-1", 111, ["MATH-DIFF-LIMIT-008"]),
  concept("MATH-DIFF-CONT-001", "미분학Ⅰ", "연속", "함수의 연속 조건", "differential-1", 120, ["MATH-DIFF-LIMIT-011"]),
  concept("MATH-DIFF-CONT-002", "미분학Ⅰ", "연속", "조각함수의 연속성과 미정계수", "differential-1", 121, ["MATH-DIFF-CONT-001"]),
  concept("MATH-DIFF-DERIV-001", "미분학Ⅰ", "미분", "미분계수의 정의와 도함수", "differential-1", 130, ["MATH-DIFF-LIMIT-008"]),
  concept("MATH-DIFF-DERIV-002", "미분학Ⅰ", "미분", "거듭제곱·다항함수 미분", "differential-1", 131, ["MATH-DIFF-DERIV-001"]),
  concept("MATH-DIFF-DERIV-003", "미분학Ⅰ", "미분", "곱의 미분법과 몫의 미분법", "differential-1", 132, ["MATH-DIFF-DERIV-002"]),
  concept("MATH-DIFF-DERIV-004", "미분학Ⅰ", "미분", "합성함수와 연쇄법칙", "differential-1", 133, ["MATH-DIFF-DERIV-002", "FND-FUNC-001"]),
  concept("MATH-DIFF-DERIV-005", "미분학Ⅰ", "미분", "음함수 미분과 로그미분", "differential-1", 134, ["MATH-DIFF-DERIV-004", "FND-LOG-001"]),
  concept("MATH-DIFF-DERIV-006", "미분학Ⅰ", "미분", "삼각·지수·로그함수 미분", "differential-1", 135, ["MATH-DIFF-DERIV-004", "FND-LOG-001", "FND-TRIG-001"]),
  concept("MATH-DIFF-APP-001", "미분학Ⅰ", "미분의 응용", "접선과 법선의 방정식", "differential-1", 140, ["MATH-DIFF-DERIV-002"]),
  concept("MATH-DIFF-APP-002", "미분학Ⅰ", "미분의 응용", "롤의 정리와 평균값정리", "differential-1", 141, ["MATH-DIFF-CONT-001", "MATH-DIFF-DERIV-002"]),
  concept("MATH-DIFF-APP-003", "미분학Ⅰ", "미분의 응용", "증가·감소와 극값 판정", "differential-1", 142, ["MATH-DIFF-DERIV-002"]),
  concept("MATH-DIFF-APP-004", "미분학Ⅰ", "미분의 응용", "오목·볼록과 변곡점", "differential-1", 143, ["MATH-DIFF-DERIV-002"]),
  concept("MATH-DIFF-APP-005", "미분학Ⅰ", "미분의 응용", "최적화 문제를 함수로 모델링하기", "differential-1", 144, ["MATH-DIFF-APP-003"]),
  concept("MATH-DIFF-LHOP-001", "미분학Ⅰ", "극한의 응용", "로피탈 정리 적용 조건", "differential-1", 145, ["MATH-DIFF-DERIV-006", "MATH-DIFF-LIMIT-008"]),

  concept("MATH-INT-BASE-001", "적분학Ⅰ", "적분의 기초", "부정적분과 원시함수의 관계", "integral-1", 201, ["MATH-DIFF-DERIV-002"], ["공통"], "현재 진도 p.25 이후 진단", "unassessed"),
  concept("MATH-INT-DEF-001", "적분학Ⅰ", "정적분", "정적분과 미적분학의 기본정리", "integral-1", 202, ["MATH-INT-BASE-001"]),
  concept("MATH-INT-SUB-001", "적분학Ⅰ", "적분 기법", "치환적분", "integral-1", 210, ["MATH-INT-BASE-001", "MATH-DIFF-DERIV-004"]),
  concept("MATH-INT-PARTS-001", "적분학Ⅰ", "적분 기법", "부분적분", "integral-1", 211, ["MATH-INT-BASE-001", "MATH-DIFF-DERIV-003"]),
  concept("MATH-INT-RATIONAL-001", "적분학Ⅰ", "적분 기법", "부분분수 분해와 유리함수 적분", "integral-1", 212, ["MATH-INT-BASE-001", "FND-ALG-002"]),
  concept("MATH-INT-TRIG-001", "적분학Ⅰ", "적분 기법", "삼각함수 적분과 삼각치환", "integral-1", 213, ["MATH-INT-BASE-001", "FND-TRIG-001"]),
  concept("MATH-INT-IMPROPER-001", "적분학Ⅰ", "이상적분", "이상적분의 수렴·발산", "integral-1", 220, ["MATH-INT-DEF-001", "MATH-DIFF-LIMIT-008"]),
  concept("MATH-INT-AREA-001", "적분학Ⅰ", "적분의 응용", "곡선 사이의 넓이", "integral-1", 230, ["MATH-INT-DEF-001"]),
  concept("MATH-INT-VOLUME-001", "적분학Ⅰ", "적분의 응용", "회전체의 부피", "integral-1", 231, ["MATH-INT-DEF-001"]),

  concept("MATH-CALC2-BASE-001", "미적분학Ⅱ", "진단", "미적분학Ⅱ 현재 시작점 진단", "calculus-2", 301, [], ["공통"], "현재 진도 p.20부터", "unassessed"),
  concept("MATH-CALC2-SEQ-001", "미적분학Ⅱ", "수열", "수열의 극한과 단조·유계", "calculus-2", 302, ["MATH-DIFF-LIMIT-008"]),
  concept("MATH-CALC2-SERIES-001", "미적분학Ⅱ", "급수", "등비급수와 p급수의 수렴", "calculus-2", 303, ["MATH-CALC2-SEQ-001"]),
  concept("MATH-CALC2-SERIES-002", "미적분학Ⅱ", "급수", "비교·비율·근 판정법", "calculus-2", 304, ["MATH-CALC2-SERIES-001"]),
  concept("MATH-CALC2-SERIES-003", "미적분학Ⅱ", "멱급수", "수렴반경과 수렴구간", "calculus-2", 305, ["MATH-CALC2-SERIES-002"]),
  concept("MATH-CALC2-SERIES-004", "미적분학Ⅱ", "Taylor 급수", "Taylor·Maclaurin 급수", "calculus-2", 306, ["MATH-CALC2-SERIES-003", "MATH-DIFF-DERIV-006"]),
  concept("MATH-CALC2-MULTI-001", "미적분학Ⅱ", "다변수 함수", "이변수 함수의 정의역과 등위곡선", "calculus-2", 320, ["MATH-CALC2-BASE-001"]),
  concept("MATH-CALC2-PARTIAL-001", "미적분학Ⅱ", "편미분", "편도함수와 고계 편도함수", "calculus-2", 321, ["MATH-CALC2-MULTI-001", "MATH-DIFF-DERIV-002"]),
  concept("MATH-CALC2-GRAD-001", "미적분학Ⅱ", "편미분", "그래디언트와 방향미분", "calculus-2", 322, ["MATH-CALC2-PARTIAL-001", "MATH-LA-VECTOR-001"]),
  concept("MATH-CALC2-DOUBLE-001", "미적분학Ⅱ", "다중적분", "이중적분과 적분 순서", "calculus-2", 330, ["MATH-INT-DEF-001", "MATH-CALC2-MULTI-001"]),
  concept("MATH-CALC2-COORD-001", "미적분학Ⅱ", "다중적분", "극좌표 변환과 Jacobian", "calculus-2", 331, ["MATH-CALC2-DOUBLE-001", "FND-TRIG-001"]),

  concept("MATH-LA-MATRIX-001", "선형대수학", "행렬", "행렬의 곱과 연산 순서", "linear-algebra", 401, [], ["공통"], "p.53~54 학습 이력 진단", "unassessed"),
  concept("MATH-LA-SYSTEM-001", "선형대수학", "연립일차방정식", "가우스 소거법과 행 사다리꼴", "linear-algebra", 402, ["MATH-LA-MATRIX-001"]),
  concept("MATH-LA-DET-001", "선형대수학", "행렬식", "행렬식의 계산과 성질", "linear-algebra", 403, ["MATH-LA-MATRIX-001"]),
  concept("MATH-LA-INV-001", "선형대수학", "역행렬", "역행렬의 존재와 계산", "linear-algebra", 404, ["MATH-LA-DET-001", "MATH-LA-SYSTEM-001"]),
  concept("MATH-LA-VECTOR-001", "선형대수학", "벡터", "벡터 기본 연산과 기하적 의미", "linear-algebra", 430, [], ["공통"], "벡터 학습 이력 진단", "unassessed"),
  concept("MATH-LA-SPACE-001", "선형대수학", "벡터공간", "span과 부분공간", "linear-algebra", 431, ["MATH-LA-VECTOR-001"]),
  concept("MATH-LA-INDEP-001", "선형대수학", "벡터공간", "선형독립과 선형종속", "linear-algebra", 432, ["MATH-LA-SPACE-001", "MATH-LA-SYSTEM-001"]),
  concept("MATH-LA-BASIS-001", "선형대수학", "벡터공간", "기저와 차원", "linear-algebra", 433, ["MATH-LA-INDEP-001"]),
  concept("MATH-LA-TRANSFORM-001", "선형대수학", "선형변환", "선형변환과 표준행렬", "linear-algebra", 440, ["MATH-LA-BASIS-001", "MATH-LA-MATRIX-001"]),
  concept("MATH-LA-EIGEN-001", "선형대수학", "고유값", "고유값과 고유벡터", "linear-algebra", 450, ["MATH-LA-DET-001", "MATH-LA-SYSTEM-001"]),
  concept("MATH-LA-DIAG-001", "선형대수학", "대각화", "대각화 가능 조건과 계산", "linear-algebra", 451, ["MATH-LA-EIGEN-001", "MATH-LA-BASIS-001"]),
  concept("MATH-LA-ORTHO-001", "선형대수학", "직교", "내적·직교·정규화", "linear-algebra", 460, ["MATH-LA-VECTOR-001"]),

  concept("MATH-ENG-ODE-001", "공업수학", "미분방정식", "미분방정식의 뜻과 해 판별", "engineering-math", 501, ["MATH-DIFF-DERIV-002"], ["서강대", "동국대", "서울시립대"], "학교별 편입 범위 대비"),
  concept("MATH-ENG-ODE-002", "공업수학", "1계 미분방정식", "변수분리형 미분방정식", "engineering-math", 502, ["MATH-ENG-ODE-001", "MATH-INT-BASE-001"], ["서강대", "동국대", "서울시립대"]),
  concept("MATH-ENG-ODE-003", "공업수학", "1계 미분방정식", "1계 선형 미분방정식과 적분인자", "engineering-math", 503, ["MATH-ENG-ODE-001", "MATH-INT-BASE-001"], ["서강대", "동국대", "서울시립대"]),
  concept("MATH-ENG-ODE-004", "공업수학", "2계 미분방정식", "상수계수 2계 동차방정식", "engineering-math", 510, ["MATH-ENG-ODE-001", "FND-EQ-001"], ["서강대", "동국대", "서울시립대"]),
  concept("MATH-ENG-ODE-005", "공업수학", "2계 미분방정식", "2계 비동차방정식의 특수해", "engineering-math", 511, ["MATH-ENG-ODE-004"], ["서강대", "동국대", "서울시립대"]),
  concept("MATH-ENG-ODE-006", "공업수학", "초기값 문제", "초기조건으로 상수 결정하기", "engineering-math", 512, ["MATH-ENG-ODE-002", "MATH-ENG-ODE-004"], ["서강대", "동국대", "서울시립대"]),
  concept("MATH-ENG-LAPLACE-001", "공업수학", "라플라스 변환", "라플라스 변환의 역할", "engineering-math", 550, ["MATH-ENG-ODE-001"], ["서강대"], "학교별 편입 범위 대비"),
  concept("MATH-ENG-LAPLACE-002", "공업수학", "라플라스 변환", "기본 함수의 라플라스 변환", "engineering-math", 551, ["MATH-ENG-LAPLACE-001", "FND-LOG-001"], ["서강대"]),
  concept("MATH-ENG-LAPLACE-003", "공업수학", "라플라스 변환", "도함수의 라플라스 변환과 초기값", "engineering-math", 552, ["MATH-ENG-LAPLACE-002", "MATH-ENG-ODE-006"], ["서강대"]),
  concept("MATH-ENG-LAPLACE-004", "공업수학", "역라플라스 변환", "부분분수와 역라플라스 변환", "engineering-math", 553, ["MATH-ENG-LAPLACE-002", "MATH-INT-RATIONAL-001"], ["서강대"]),
];
