window.TRANSFER_MATH_PROBLEMS = [
  {
    id: "P-FND-ABS-001",
    conceptIds: ["FND-ABS-001"],
    type: "concept-choice",
    prompt: "|x-2| < 1을 x의 범위로 바꾸면 무엇인가요?",
    math: "|x - 2| < 1",
    choices: ["1 < x < 3", "-1 < x < 1", "x < 1 또는 x > 3", "2 < x < 3"],
    answer: "1 < x < 3",
    solutionSteps: ["-1 < x-2 < 1로 바꿉니다.", "세 항에 2를 더합니다.", "1 < x < 3을 얻습니다."],
    difficulty: 1,
    sourceType: "chatgpt-derived"
  },
  {
    id: "P-FND-ALG-001",
    conceptIds: ["FND-ALG-001"],
    type: "concept-choice",
    prompt: "x²-4를 올바르게 인수분해한 것은 무엇인가요?",
    math: "x² - 4",
    choices: ["(x-2)(x+2)", "(x-2)²", "(x-4)(x+1)", "x(x-4)"],
    answer: "(x-2)(x+2)",
    solutionSteps: ["4=2²이므로 두 제곱의 차입니다.", "a²-b²=(a-b)(a+b)를 적용합니다."],
    difficulty: 1,
    sourceType: "chatgpt-derived"
  },
  {
    id: "P-DIFF-LIMIT-001-A",
    conceptIds: ["MATH-DIFF-LIMIT-001"],
    type: "concept-choice",
    prompt: "ε-δ 정의에서 δ가 직접 제한하는 것은 무엇인가요?",
    math: "0 < |x-a| < δ  ⇒  |f(x)-L| < ε",
    choices: ["x와 a 사이의 거리", "f(x)와 L 사이의 거리", "함수 f의 기울기", "ε의 크기"],
    answer: "x와 a 사이의 거리",
    solutionSteps: ["δ는 입력 쪽 조건에 등장합니다.", "따라서 |x-a|, 즉 x와 a 사이의 거리를 제한합니다."],
    difficulty: 1,
    sourceType: "chatgpt-derived"
  },
  {
    id: "P-DIFF-LIMIT-001-B",
    conceptIds: ["MATH-DIFF-LIMIT-001"],
    type: "next-step",
    prompt: "x→2인 극한에서 δ를 정했다는 말의 가장 정확한 뜻은 무엇인가요?",
    choices: ["|x-2|가 허용되는 최대 범위를 정했다", "|f(x)-L|을 δ보다 작게 만들었다", "x를 정확히 2로 고정했다", "ε와 δ가 항상 같다고 정했다"],
    answer: "|x-2|가 허용되는 최대 범위를 정했다",
    solutionSteps: ["δ는 x가 2에 얼마나 가까워야 하는지를 정하는 값입니다.", "x=2 자체를 요구하는 것은 아닙니다."],
    difficulty: 1,
    sourceType: "chatgpt-derived"
  },
  {
    id: "P-DIFF-LIMIT-002-A",
    conceptIds: ["MATH-DIFF-LIMIT-002"],
    type: "next-step",
    prompt: "|x²-4|를 δ와 연결하기 위한 첫 식 변형으로 가장 적절한 것은 무엇인가요?",
    math: "|x² - 4|",
    choices: ["|x-2||x+2|", "|x-4||x+1|", "|x-2|²", "|x|²-4"],
    answer: "|x-2||x+2|",
    solutionSteps: ["x²-4=(x-2)(x+2)입니다.", "절댓값의 곱 성질로 |x-2||x+2|가 됩니다."],
    difficulty: 1,
    sourceType: "chatgpt-derived"
  },
  {
    id: "P-DIFF-LIMIT-003-A",
    conceptIds: ["MATH-DIFF-LIMIT-003"],
    type: "concept-choice",
    prompt: "|x²-4|=|x-2||x+2|에서 δ로 바로 통제되지 않는 인자는 무엇인가요?",
    choices: ["|x+2|", "|x-2|", "둘 다 이미 상수", "ε"],
    answer: "|x+2|",
    solutionSteps: ["δ는 |x-2|를 제한할 수 있습니다.", "|x+2|에는 별도의 상한이 필요합니다."],
    difficulty: 1,
    sourceType: "chatgpt-derived"
  },
  {
    id: "P-DIFF-LIMIT-004-A",
    conceptIds: ["MATH-DIFF-LIMIT-004"],
    type: "concept-choice",
    prompt: "풀이에서 |x-2|<1이라는 조건을 추가하는 주된 이유는 무엇인가요?",
    math: "|x-2| < 1",
    choices: ["|x+2|에 고정된 상한을 만들기 위해", "ε=1이라고 정하기 위해", "x를 1로 대입하기 위해", "δ가 항상 1이라는 것을 증명하기 위해"],
    answer: "|x+2|에 고정된 상한을 만들기 위해",
    solutionSteps: ["|x-2|<1이면 1<x<3입니다.", "그러면 3<x+2<5이므로 |x+2|<5입니다.", "1은 |x+2|의 상한을 만들기 위한 보조 조건입니다."],
    difficulty: 2,
    sourceType: "chatgpt-derived"
  },
  {
    id: "P-DIFF-LIMIT-004-B",
    conceptIds: ["MATH-DIFF-LIMIT-004", "FND-ABS-001"],
    type: "next-step",
    prompt: "|x-2|<1에서 얻은 1<x<3을 이용하면 |x+2|에 대해 어떤 상한을 얻을 수 있나요?",
    choices: ["|x+2|<5", "|x+2|<1", "|x+2|<3", "|x+2|<ε"],
    answer: "|x+2|<5",
    solutionSteps: ["1<x<3에 2를 더하면 3<x+2<5입니다.", "이 구간에서는 x+2가 양수이므로 |x+2|<5입니다."],
    difficulty: 2,
    sourceType: "chatgpt-derived"
  },
  {
    id: "P-DIFF-LIMIT-005-A",
    conceptIds: ["MATH-DIFF-LIMIT-005"],
    type: "next-step",
    prompt: "|x²-4|<5|x-2|까지 얻었습니다. 이 값을 ε보다 작게 만들기 위한 충분조건은 무엇인가요?",
    math: "|x²-4| < 5|x-2| < ε",
    choices: ["|x-2|<ε/5", "|x-2|<5ε", "|x-2|<5/ε", "|x-2|<ε+5"],
    answer: "|x-2|<ε/5",
    solutionSteps: ["5|x-2|<ε를 원합니다.", "양변을 5로 나누면 |x-2|<ε/5입니다."],
    difficulty: 2,
    sourceType: "chatgpt-derived"
  },
  {
    id: "P-DIFF-LIMIT-006-A",
    conceptIds: ["MATH-DIFF-LIMIT-006"],
    type: "concept-choice",
    prompt: "δ≤1과 δ≤ε/5를 동시에 만족시키기 위한 선택은 무엇인가요?",
    choices: ["δ=min{1, ε/5}", "δ=max{1, ε/5}", "δ=1+ε/5", "δ=5ε"],
    answer: "δ=min{1, ε/5}",
    solutionSteps: ["δ가 두 값보다 모두 작거나 같아야 합니다.", "따라서 두 후보 중 작은 값을 선택합니다."],
    difficulty: 2,
    sourceType: "chatgpt-derived"
  },
  {
    id: "P-DIFF-LIMIT-006-B",
    conceptIds: ["MATH-DIFF-LIMIT-006"],
    type: "error-find",
    prompt: "어떤 풀이가 δ=max{1, ε/5}로 정했습니다. 가장 핵심적인 문제는 무엇인가요?",
    choices: ["큰 값을 고르면 둘 중 하나의 제한을 위반할 수 있다", "max는 수학에서 사용할 수 없는 함수다", "ε는 δ보다 항상 커야 한다", "1을 사용하면 안 된다"],
    answer: "큰 값을 고르면 둘 중 하나의 제한을 위반할 수 있다",
    solutionSteps: ["두 조건은 δ≤1과 δ≤ε/5입니다.", "max를 고르면 더 작은 쪽의 조건을 넘을 수 있습니다."],
    difficulty: 2,
    sourceType: "chatgpt-derived"
  },
  {
    id: "P-DIFF-LIMIT-007-A",
    conceptIds: ["MATH-DIFF-LIMIT-007"],
    type: "concept-choice",
    prompt: "√(x-1)-2 같은 제곱근의 차를 x-5와 연결할 때 흔히 사용하는 방법은 무엇인가요?",
    choices: ["켤레식을 곱해 유리화한다", "양변에 로그를 취한다", "부분적분한다", "행렬식으로 바꾼다"],
    answer: "켤레식을 곱해 유리화한다",
    solutionSteps: ["(√(x-1)-2)(√(x-1)+2)=x-5입니다.", "이렇게 |x-5|를 만들면 δ와 연결할 수 있습니다."],
    difficulty: 2,
    sourceType: "chatgpt-derived"
  },
  {
    id: "P-DIFF-CONT-001",
    conceptIds: ["MATH-DIFF-CONT-001"],
    type: "concept-choice",
    prompt: "x=a에서 함수가 연속이기 위한 조건으로 옳은 것은 무엇인가요?",
    choices: ["f(a)가 정의되고 lim x→a f(x)가 존재하며 둘이 같다", "f(a)만 정의되면 된다", "좌극한만 존재하면 된다", "도함수가 반드시 0이어야 한다"],
    answer: "f(a)가 정의되고 lim x→a f(x)가 존재하며 둘이 같다",
    solutionSteps: ["함숫값이 정의되어야 합니다.", "극한이 존재해야 합니다.", "극한값과 함숫값이 같아야 합니다."],
    difficulty: 1,
    sourceType: "curriculum-original"
  },
  {
    id: "P-INT-BASE-001",
    conceptIds: ["MATH-INT-BASE-001"],
    type: "concept-choice",
    prompt: "∫2x dx의 결과로 올바른 것은 무엇인가요?",
    choices: ["x²+C", "2x²+C", "x+C", "2+C"],
    answer: "x²+C",
    solutionSteps: ["x²을 미분하면 2x입니다.", "부정적분이므로 적분상수 C를 붙입니다."],
    difficulty: 1,
    sourceType: "diagnostic-original"
  },
  {
    id: "P-CALC2-BASE-001",
    conceptIds: ["MATH-CALC2-BASE-001"],
    type: "concept-choice",
    prompt: "미적분학Ⅱ 진단입니다. 여러 변수의 함수 f(x,y)에서 x에 대해서만 미분하고 y는 상수처럼 다루는 연산은 무엇인가요?",
    choices: ["편미분", "부분적분", "전치", "라플라스 변환"],
    answer: "편미분",
    solutionSteps: ["여러 변수 중 하나만 변화시키고 나머지는 고정해 미분하는 것을 편미분이라고 합니다."],
    difficulty: 1,
    sourceType: "diagnostic-original"
  },
  {
    id: "P-LA-MATRIX-001",
    conceptIds: ["MATH-LA-MATRIX-001"],
    type: "concept-choice",
    prompt: "A가 2×3 행렬이고 B가 3×4 행렬일 때 AB의 크기는 무엇인가요?",
    choices: ["2×4", "3×3", "4×2", "AB는 정의되지 않는다"],
    answer: "2×4",
    solutionSteps: ["안쪽 차원 3과 3이 같으므로 곱이 정의됩니다.", "결과 크기는 바깥 차원인 2×4입니다."],
    difficulty: 1,
    sourceType: "diagnostic-original"
  },
  {
    id: "P-LA-VECTOR-001",
    conceptIds: ["MATH-LA-VECTOR-001"],
    type: "concept-choice",
    prompt: "벡터 (1,2)와 (3,-1)의 합은 무엇인가요?",
    choices: ["(4,1)", "(3,2)", "(4,-2)", "(3,-1)"],
    answer: "(4,1)",
    solutionSteps: ["같은 위치의 성분끼리 더합니다.", "1+3=4, 2+(-1)=1입니다."],
    difficulty: 1,
    sourceType: "diagnostic-original"
  },
  {
    id: "P-ENG-ODE-001",
    conceptIds: ["MATH-ENG-ODE-001"],
    type: "concept-choice",
    prompt: "다음 중 미분방정식인 것은 무엇인가요?",
    choices: ["y'=2y", "x²-4=0", "2x+3=7", "A+B=C"],
    answer: "y'=2y",
    solutionSteps: ["미지의 함수 y와 그 도함수 y'가 함께 나타납니다.", "따라서 미분방정식입니다."],
    difficulty: 1,
    sourceType: "diagnostic-original"
  },
  {
    id: "P-ENG-LAPLACE-001",
    conceptIds: ["MATH-ENG-LAPLACE-001"],
    type: "concept-choice",
    prompt: "라플라스 변환을 미분방정식 풀이에 사용하는 핵심 이유는 무엇인가요?",
    choices: ["미분 연산을 s에 대한 대수 연산으로 바꾸기 위해", "행렬을 대각화하기 위해", "복소수를 없애기 위해", "적분상수를 자동으로 0으로 만들기 위해"],
    answer: "미분 연산을 s에 대한 대수 연산으로 바꾸기 위해",
    solutionSteps: ["라플라스 변환은 미분 항을 s를 포함한 대수식으로 바꿉니다.", "대수식을 푼 뒤 역변환하여 원래 함수로 돌아옵니다."],
    difficulty: 1,
    sourceType: "curriculum-original"
  }
];
